name: CI

on:
    push:
        branches:
            - "*"

jobs:
    test:
        name: Tests check
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Setup Python
              uses: actions/setup-python@v4
              with:
                python-version: '3.x'
            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip setuptools coverage
                pip install .
            - name: Test and create coverage report
              run: |
                python -m coverage run --source src -m unittest
                python -m coverage report >> .coverage_report
            - uses: actions/upload-artifact@v4
              with:
                name: coverage-report
                path: .coverage_report
    coverage:
        name: Test coverage check
        runs-on: ubuntu-latest
        steps:
            - uses: actions/download-artifact@v4
              with: 
                name: coverage-report
            - name: Check coverage report
              uses: orgoro/coverage@v3.1
              with:
                  coverageFile: .coverage_report
                  token: ${{ secrets.GITHUB_TOKEN }}

            


              
            
                  
